#F2 Swim
library(readxl)
f2_idv <- read_xlsx(file.choose())
f2_idv$treatment <- as.factor(f2_idv$treatment)
f2_idv$sex <- as.factor(f2_idv$sex)
shapiro.test(f2_idv$`distance_swam(cm)`)
str(f2_idv)
model <- aov(f2_idv$`distance_swam(cm)` ~ f2_idv$treatment * f2_idv$sex, data = f2_idv)
summary(model)
TukeyHSD(model)
#F1 Swim
f1_idv <- read_xlsx(file.choose())
f1_idv$treatment <- as.factor(f1_idv$treatment)
f1_idv$sex <- as.factor(f1_idv$sex)
shapiro.test(f1_idv$`distance_swam(cm)`)
str(f1_idv)
model <- lm(f1_idv$`distance_swam(cm)` ~ f1_idv$treatment * f1_idv$sex, data = f1_idv)
summary(model)
TukeyHSD(model)

#F0 Swim
f0_idv <- read_xlsx(file.choose())
f0_idv$treatment <- as.factor(f0_idv$treatment)
f0_idv$sex <- as.factor(f0_idv$sex)
shapiro.test(f0_idv$`distance_swam(cm)`)
str(f0_idv)
model <- glm(f0_idv$`distance_swam(cm)` ~ f0_idv$treatment * f0_idv$sex, data = f0_idv)
summary(model)
TukeyHSD(model)
